### ISSUE TITLE
[Meta/Maintenance]: Update default branch name so it's not master

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#3195]
### Describe the feature you'd like

Think we should update the default branch name to get with the times.
Not had any complaints or seen anyone take offence (For BookStack) but might as well change it since `master` is not overly descriptive and there may be those that are privately offended or feel awkward using `master`. Not much hassle on our side to accommodate that.

I've changed the other BookStackApp repos to use `main`, but thinking we'd be better off with `dev` / `develop` / `development` since that better describes the main purpose of the default BookStack branch and may provide an obvious indicator for people on the wrong branch.

Should be relatively easy to change, thanks to most people using the `release` branch. Thinking it should only really affect current active developers. From experience, GitHub should redirect existing links to the new default branch which acts as a nice backup for old references.

#### Areas to update

- [x] Website references (If any)
- [x] GitHub action branch references
- [x] Maintainer scripts (In devops repo)
- [x] Integrations
  - [x] CrowdIn
  - [x] StyleCI
  - [x] Code Climate

**Comment by ssddanbrown** [comment]
Complete! May be other references out there but should be redirected by GitHub to new develop references.
