### ISSUE TITLE
PHP Requirment Change

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#4029]
Changes from PHP 7.4 to PHP 8.0.2 for next feature release.

#### Todo

- [x] Assess scripts that need to be updated.
- [x] Update scripts as required. - [Scripts updated](https://github.com/BookStackApp/devops/commit/b8d746437b5ee8a21ec0a386c1e97c419b78c321)
  - [x] 20.04 install script
  - [x] 18.04 install script
  - [x] 16.04 update script to indicate no longer supported. 
- [x] Prepare guidance for supported systems that may need updating.
- [x] Check popular distribution options:
  - [x] Linuxserver docker image - php81
  - [x] Solidnerd docker image - php:8.2
  - [x] Hassio setup - php81
  - [x] Turnkey Linux - [Raised here](https://github.com/turnkeylinux-apps/bookstack/issues/1), in progress to be php8.1.

#### Docs Update

- [x] Blogpost release notice
- [x] Update version notice
- [x] Update install script details with new php versions used. 
- [x] Update installation requirements. 

#### Update Commands

For installs that have used our Ubuntu 18.04 and Ubuntu 20.04 install scripts, PHP can be upgraded to 8.2 using the below commands. Installations via our Ubuntu 22.04 install script are already using PHP 8.1 and therefore they don't need to be upgraded at this time.

Warning: if you run other applications on this machine, PHP applications in particular, then those may be affected by these changes also.

```bash
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install -y php8.2 php8.2-curl php8.2-mbstring php8.2-ldap php8.2-xml php8.2-zip php8.2-gd php8.2-mysql libapache2-mod-php8.2
sudo a2dismod php7.2 php7.4 php7.3 php8.0 php8.1
sudo a2enmod php8.2
sudo systemctl restart apache2
```

You may also need to update `composer` to be compatible with php8.2. 
**Link to composer update docs, maybe extract to it's own section with update docs?**

*Tested the above on Ubuntu 20.04 and Ubuntu 18.04 and Previously-upgrade-to-php8-18.04 environments*
