### ISSUE TITLE
PHP Requirement Change: 8.0 to 8.1

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/BookStack#4893]
Changes from PHP 8.0 to PHP 8.1 for next feature release.

#### Todo

- [x] Update codebase minimums
- [x] Assess scripts that need to be updated.
- [x] Update scripts as required
  - [x] 22.04 install script  - (Already installing 8.1)
  - [x] 20.04 install script  - (Already installing 8.2)
  - [x] 18.04 install script - (Already installing 8.2)
- [x] Prepare general guidance for supported systems that may need updating.
  - [x] Test on an older ~18.04~ 20.04 install script install
    - 18.04 went out of support last year. Instead tested a plain 20.04 (PHP 7.4) upgrading using commands. Worked fine.
- [x] Check popular distribution options:
  - [x] Linuxserver docker image - PHP 8.3
  - [x] Solidnerd docker image - PHP 8.3
  - [x] Hassio setup - PHP 8.2
  - [x] Turnkey Linux - PHP 8.2

#### Docs Update

- [x] Blogpost release notice
- [ ] Update version notice
- [x] Update install script details with new php versions used. 
- [x] Update installation requirements. 

#### Update Commands

You'll need to update PHP if using a version lower than 8.1. You can usually check your installed PHP version by running `php -v` but in some cases your web-server could be running a different PHP version than what the command line reflects. The commands below provide an example of how PHP can be updated to the latest version (8.3) on most Debian & Ubuntu based systems.

**Warnings:** 
  - In most cases, especially if installed using our scripts and updating from a recent BookStack version, you won't need to update PHP using the below as you'll already be using PHP 8.1 or greater.
  - If you run other applications on this machine, PHP applications in particular, then those may be affected by these changes also.

```bash
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install -y php8.3 php8.3-curl php8.3-mbstring php8.3-ldap php8.3-xml php8.3-zip php8.3-gd php8.3-mysql libapache2-mod-php8.3
sudo a2dismod php7.4 php8.0 php8.1 php8.2
sudo a2enmod php8.3
sudo systemctl restart apache2
```

You may also need to [update `composer`](/docs/admin/updates/#updating-composer) to be compatible with php8.3.
